<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            [
                'full_name' => 'Andi Pratama',
                'email' => 'andi.pratama@example.com',
                'phone_number' => '081234567891',
                'nrp' => 'TA.XI.23.075',
                'password' => Hash::make('password'),
                'generation' => 'XIV',
                'batch' => '2023',
                'major' => 'Sistem Informasi',
                'photo' => 'imgUsers/user-01.jpg',
                'birth_date' => '2003-07-14',
                'status' => 'active',
                'gender' => 'male',
                'position' => 'leader',
                'role' => 'admin',
            ],
            [
                'full_name' => 'Dewi Lestari',
                'email' => 'dewi.lestari@example.com',
                'phone_number' => '081234567892',
                'nrp' => 'TA.XI.23.076',
                'password' => Hash::make('password'),
                'generation' => 'XIV',
                'batch' => '2023',
                'major' => 'Perhotelan',
                'photo' => 'imgUsers/user-02.jpg',
                'birth_date' => '2004-02-09',
                'status' => 'inactive',
                'gender' => 'female',
                'position' => 'secretary',
                'role' => 'member',
            ],
            [
                'full_name' => 'Rizky Saputra',
                'email' => 'rizky.saputra@example.com',
                'phone_number' => '081234567893',
                'nrp' => 'TA.XI.23.077',
                'password' => Hash::make('password'),
                'generation' => 'XIV',
                'batch' => '2023',
                'major' => 'Sistem Informasi',
                'photo' => 'imgUsers/user-03.jpg',
                'birth_date' => '2002-11-25',
                'status' => 'alumni',
                'gender' => 'male',
                'position' => 'logistics',
                'role' => 'logistics',
            ],
            [
                'full_name' => 'Siti Rahmawati',
                'email' => 'siti.rahmawati@example.com',
                'phone_number' => '081234567894',
                'nrp' => 'TA.XI.23.078',
                'password' => Hash::make('password'),
                'generation' => 'XV',
                'batch' => '2024',
                'major' => 'Perhotelan',
                'photo' => 'imgUsers/user-04.jpg',
                'birth_date' => '2005-03-02',
                'status' => 'active',
                'gender' => 'female',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Budi Santoso',
                'email' => 'budi.santoso@example.com',
                'phone_number' => '081234567895',
                'nrp' => 'TA.XI.23.079',
                'password' => Hash::make('password'),
                'generation' => 'XV',
                'batch' => '2024',
                'major' => 'Sistem Informasi',
                'photo' => 'imgUsers/user-05.jpg',
                'birth_date' => '2003-09-30',
                'status' => 'inactive',
                'gender' => 'male',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Nadia Putri',
                'email' => 'nadia.putri@example.com',
                'phone_number' => '081234567896',
                'nrp' => 'TA.XI.23.080',
                'password' => Hash::make('password'),
                'generation' => 'XV',
                'batch' => '2024',
                'major' => 'Perhotelan',
                'photo' => 'imgUsers/user-06.jpg',
                'birth_date' => '2004-06-21',
                'status' => 'active',
                'gender' => 'female',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Rafi Kurniawan',
                'email' => 'rafi.kurniawan@example.com',
                'phone_number' => '081234567897',
                'nrp' => 'TA.XI.23.081',
                'password' => Hash::make('password'),
                'generation' => 'XV',
                'batch' => '2024',
                'major' => 'Sistem Informasi',
                'photo' => 'imgUsers/user-07.jpg',
                'birth_date' => '2002-08-17',
                'status' => 'alumni',
                'gender' => 'male',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Fitri Handayani',
                'email' => 'fitri.handayani@example.com',
                'phone_number' => '081234567898',
                'nrp' => 'TA.XI.23.082',
                'password' => Hash::make('password'),
                'generation' => 'XVI',
                'batch' => '2025',
                'major' => 'Perhotelan',
                'photo' => 'imgUsers/user-08.jpg',
                'birth_date' => '2005-01-13',
                'status' => 'active',
                'gender' => 'female',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Yoga Prasetyo',
                'email' => 'yoga.prasetyo@example.com',
                'phone_number' => '081234567899',
                'nrp' => 'TA.XI.23.083',
                'password' => Hash::make('password'),
                'generation' => 'XVI',
                'batch' => '2025',
                'major' => 'Sistem Informasi',
                'photo' => 'imgUsers/user-09.jpg',
                'birth_date' => '2004-10-04',
                'status' => 'inactive',
                'gender' => 'male',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Melisa Anggraini',
                'email' => 'melisa.anggraini@example.com',
                'phone_number' => '081234567900',
                'nrp' => 'TA.XI.23.084',
                'password' => Hash::make('password'),
                'generation' => 'XVI',
                'batch' => '2025',
                'major' => 'Perhotelan',
                'photo' => 'imgUsers/user-10.jpg',
                'birth_date' => '2003-04-26',
                'status' => 'alumni',
                'gender' => 'female',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Fahriansyah Putra',
                'email' => 'fahriansyah.putra@example.com',
                'phone_number' => '081234567901',
                'nrp' => 'TA.XI.23.085',
                'password' => Hash::make('password'),
                'generation' => 'XVI',
                'batch' => '2025',
                'major' => 'Sistem Informasi',
                'photo' => 'imgUsers/user-11.jpg',
                'birth_date' => '2005-12-09',
                'status' => 'active',
                'gender' => 'male',
                'position' => 'member',
                'role' => 'member',
            ],
            [
                'full_name' => 'Citra Ayu',
                'email' => 'citra.ayu@example.com',
                'phone_number' => '081234567902',
                'nrp' => 'TA.XI.23.086',
                'password' => Hash::make('password'),
                'generation' => 'XVI',
                'batch' => '2025',
                'major' => 'Perhotelan',
                'photo' => 'imgUsers/user-12.jpg',
                'birth_date' => '2002-05-18',
                'status' => 'inactive',
                'gender' => 'female',
                'position' => 'member',
                'role' => 'member',
            ],
        ]);
    }
}
